services:
  companion:
    build: ./browser_companion
    shm_size: "1gb"
    ports:
      - "5800:5800"
      - "8100:8100"
    environment:
      CHROMIUM_REMOTE_DEBUGGING: "1"
      CHROMIUM_REMOTE_DEBUGGING_PORT: "9222"
      CHROMIUM_CUSTOM_ARGS: "--incognito"
      KEEP_APP_RUNNING: "1"
      DISPLAY_WIDTH: "1280"
      DISPLAY_HEIGHT: "800"
      USER_ID: "1000"
      GROUP_ID: "1000"
    volumes:
      - companion-config:/config

volumes:
  companion-config:
