"""Client and Home Assistant helpers for the Browser Companion add-on."""

from __future__ import annotations

from .client import (
    API_PORT,
    DEFAULT_TIMEOUT,
    FALLBACK_BASE_URL,
    FALLBACK_SLUG,
    HEALTH_TIMEOUT,
    KNOWN_SLUGS,
    SLUG_SUFFIX,
    BrowserCompanionClient,
    CompanionEndpoint,
    CompanionError,
    addon_is_available,
    addon_state,
    async_create_session,
    async_delete_session,
    async_discover_base_url,
    async_discover_companion,
    async_get_session,
    async_health_ok,
    async_wait_captured,
    base_url_from_slug,
    candidate_base_urls,
    captured_cookie,
    captured_query,
    companion_placeholders,
    companion_redirect_href,
    companion_ui_url,
    hostname_from_addon_slug,
    ingress_path,
    is_companion_slug,
    slug_from_api_base,
    supervisor_present,
)
from .flow import CompanionLoginFlow, CompanionStart

__version__ = "0.1.1"

__all__ = [
    "API_PORT",
    "DEFAULT_TIMEOUT",
    "FALLBACK_BASE_URL",
    "FALLBACK_SLUG",
    "HEALTH_TIMEOUT",
    "KNOWN_SLUGS",
    "SLUG_SUFFIX",
    "BrowserCompanionClient",
    "CompanionEndpoint",
    "CompanionError",
    "CompanionLoginFlow",
    "CompanionStart",
    "__version__",
    "addon_is_available",
    "addon_state",
    "async_create_session",
    "async_delete_session",
    "async_discover_base_url",
    "async_discover_companion",
    "async_get_session",
    "async_health_ok",
    "async_wait_captured",
    "base_url_from_slug",
    "candidate_base_urls",
    "captured_cookie",
    "captured_query",
    "companion_placeholders",
    "companion_redirect_href",
    "companion_ui_url",
    "hostname_from_addon_slug",
    "ingress_path",
    "is_companion_slug",
    "slug_from_api_base",
    "supervisor_present",
]
